### ISSUE TITLE
Kitty does not respect Dvorak on OS X 10.11.6 (15G1212)

### ISSUE THREAD

**Issue by somebehemoth** [kovidgoyal/kitty#29]
I use Dvorak keyboard layout and the shortcuts shown on https://github.com/kovidgoyal/kitty only work with the physical qwerty keys. Is there some setting I am missing?  I am new to the project and I like this app.  Thank you.

Steps to reproduce: 

1. Use Dvorak keyboard layout
2. start kitty
3. `ctrl + shift + Enter` to make new window
4. `ctrl + shift + w` expected to close new window, but does not
5. `ctrl + shift + ,` closes new window as expected

**Comment by kovidgoyal** [comment]
Same issue as #17 you can try the patch linked to there and see if it helps.

**Comment by somebehemoth** [comment]
As I understand it, this is a bug in glfw and as such will not be fixed in this project.  However, as the patch in #17 was rejected I was wondering if you plan to support DVORAK on Mac in the future roadmap.  I understand this is not a common configuration.  Thank you

**Comment by kovidgoyal** [comment]
I haven't said I wont workaround it in kitty -- I just need to find a workaround that is more robust than the one in that patch. In the meantime just use that patch, it should work for most people.

**Comment by kovidgoyal** [comment]
I have implemented a fix, please test.

**Comment by somebehemoth** [comment]
I pulled the latest from master and ran:
`/Users/Shared/buildbot/sw/sw/bin/python3 .`

Kitty still starts but now the shortcuts are not working. I get the following in the console on every key press:

`AttributeError: module 'kitty.fast_data_types' has no attribute 'glfw_get_key_name'
Traceback (most recent call last):
  File "./kitty/boss.py", line 56, in f
  File "./kitty/boss.py", line 262, in on_key
  File "./kitty/keys.py", line 88, in get_shortcut
  File "./kitty/keys.py", line 58, in get_localized_key
AttributeError: module 'kitty.fast_data_types' has no attribute 'glfw_get_key_name'
...
`

Thank you

**Comment by kovidgoyal** [comment]
You need to run

 python3 setup.py build

 again

**Comment by somebehemoth** [comment]
My mistake, thank you.  Dvorak shortcuts are all working as expected except for (curiously):
`ctrl + shift + [`
and
`ctrl + shift + ]`

I can still get the commands for these shortcuts to work in Dvorak land by using:
`ctrl + shift + /`
and
`ctrl + shift + =`

Thank you improving kitty so it works better in OS X with Dvorak.

**Comment by kovidgoyal** [comment]
Forgot a few keys -- see https://github.com/kovidgoyal/kitty/commit/ac53776ee4cf20be28e1c02ccfcd7e92b963b7e3

**Comment by somebehemoth** [comment]
This is working as expected, thank you!  Before i open a new issue; I am having some weirdness with regards to the keyboard but I want to be sure this isn't already known:

- Backspace does not work.  
- ctrl + r does not work to recursively search bash history.
- Tying `ls + Enter` works but kitty shows me that I typed `lls`. This is not limited to `ls`, other characters are appearing unexpectedly the longer the string, for example typing `tail` works but in kitty I see `ttaaitail`.  The sytax highlighting is odd for this example too (see attached demonstrating that `tail` works but with weirdness).  I am wondering if there is something I need to change in kitty.conf or elsewhere.
![screen shot 2017-01-12 at 10 16 51](https://cloud.githubusercontent.com/assets/643326/21895428/b4b8e266-d8b0-11e6-85c5-0e40f5a2b492.png)

**Comment by kovidgoyal** [comment]
I can reproduce none of those issues on linux, it's likely something specific to OS X or OS X + whatever technique you are using to remap the keys to dvorak. Unfortunately, I dont have an OS X machine I can test on so it is hard for me to say more. Try posting in #5 and see if any of the other OS X users can reproduce the problem.

**Comment by somebehemoth** [comment]
For what it is worth I switched back to Qwerty and got the same behavior.  As you say this is likely something specific to my setup and OS X.  I'll post over in #5 as soon as I can and see if anyone else had this problem.  Thank you again for everything!

**Comment by somebehemoth** [comment]
Just to follow up, the character anomalies reported above were caused by: https://github.com/zsh-users/zsh-syntax-highlighting

My inability to use backspace seems to be related to ZSH. When I switch to bash it works as expected.

My inability to ctrl+r is also zsh related as it works as expected when I switch to bash.

Just offering these as data points in case future users of ZSH have trouble.  My ZSH setup is highly customized so it is possible the problems above were not caused by ZSH per se, but some setup I've made that, for whatever reason, does not play nice with Kitty.  

Thank you

**Comment by kovidgoyal** [comment]
Just FYI I use zsh also and see none of those issues. I do have the following section in my zshrc regarding keyboard handling, maybe you can try it:

```
    # Support non-standard keys
    zmodload zsh/terminfo
    # create a zkbd compatible hash;
    # to add other keys to this hash, see: man 5 terminfo
    typeset -A key

    key[Home]=${terminfo[khome]}
    key[End]=${terminfo[kend]}
    key[Insert]=${terminfo[kich1]}
    key[Delete]=${terminfo[kdch1]}
    key[Up]=${terminfo[kcuu1]}
    key[Down]=${terminfo[kcud1]}
    key[Left]=${terminfo[kcub1]}
    key[Right]=${terminfo[kcuf1]}
    key[PageUp]=${terminfo[kpp]}
    key[PageDown]=${terminfo[knp]}
    key[BackTab]=${terminfo[kcbt]}

    # Have the up/down arrow keys search through history for the current prefix 
    autoload -U up-line-or-beginning-search
    autoload -U down-line-or-beginning-search
    zle -N up-line-or-beginning-search
    zle -N down-line-or-beginning-search

    # setup key accordingly
    [[ -n "${key[Home]}"    ]]  && bindkey  "${key[Home]}"    beginning-of-line
    [[ -n "${key[End]}"     ]]  && bindkey  "${key[End]}"     end-of-line
    [[ -n "${key[Insert]}"  ]]  && bindkey  "${key[Insert]}"  overwrite-mode
    [[ -n "${key[Delete]}"  ]]  && bindkey  "${key[Delete]}"  delete-char
    [[ -n "${key[Up]}"      ]]  && bindkey  "${key[Up]}"      up-line-or-beginning-search
    [[ -n "${key[Down]}"    ]]  && bindkey  "${key[Down]}"    down-line-or-beginning-search
    [[ -n "${key[Left]}"    ]]  && bindkey  "${key[Left]}"    backward-char
    [[ -n "${key[Right]}"   ]]  && bindkey  "${key[Right]}"   forward-char

```

I dont use incremental search through history, so I dont have a key binding for it. You can add backspace to the list of keys, with

    key[Backspace]=${terminfo[kbs]}
    key[BackSpace]=${terminfo[kbs]}
