### ISSUE TITLE
Cpu usage is high when multi tabs opened in 0.43.1

### ISSUE THREAD

**Issue by SaltyKitkat** [kovidgoyal/kitty#9071]
**Describe the bug**

**To Reproduce**
- Launch kitty, run htop in the first tab.
- Currently cpu usage is normal(quite low to nearly 0%).
- open a new tab, and switch to the previous tab to check the cpu usage.
- The cpu usage of kitty is around 5%, which is very high compared to previous versions.
  (BTW, the cpu usage of kwin_wayland is also increased to ~12%)
- Close the second tab, the cpu usage go down to nearly 0% as normal.

**Environment details**
```
kitty 0.43.1 created by Kovid Goyal
Linux SaltyKitkat 6.16.10 #1-NixOS SMP PREEMPT Sun Jul 27 21:26:38 UTC 2025 x86_64
<<< Welcome to NixOS 25.11.20251002.7df7ff7 (x86_64) - /dev/tty >>>
DISTRIB_CODENAME=xantusia
DISTRIB_DESCRIPTION="NixOS 25.11 (Xantusia)"
DISTRIB_ID=nixos
DISTRIB_RELEASE="25.11"
LSB_VERSION="25.11 (Xantusia)"
Running under: Wayland (kwin 6.4.5)
OpenGL: '4.6 (Core Profile) Mesa 25.2.4' Detected version: 4.6
Frozen: False
Fonts:
  medium: FiraMonoNF-Regular: /nix/store/qm3frpijz598yvl1d4xjx0gv0dj7ra5b-nerd-fonts-fira-mono-3.4.0+3.206/share/fonts/opentype/NerdFonts/FiraMono/FiraMonoNerdFont-Regular.otf:0
          Features: ()
    bold: FiraMonoNF-Bold: /nix/store/qm3frpijz598yvl1d4xjx0gv0dj7ra5b-nerd-fonts-fira-mono-3.4.0+3.206/share/fonts/opentype/NerdFonts/FiraMono/FiraMonoNerdFont-Bold.otf:0
          Features: ()
  italic: FiraMonoNF-Medium: /nix/store/qm3frpijz598yvl1d4xjx0gv0dj7ra5b-nerd-fonts-fira-mono-3.4.0+3.206/share/fonts/opentype/NerdFonts/FiraMono/FiraMonoNerdFont-Medium.otf:0
          Features: ()
      bi: FiraMonoNF-Bold: /nix/store/qm3frpijz598yvl1d4xjx0gv0dj7ra5b-nerd-fonts-fira-mono-3.4.0+3.206/share/fonts/opentype/NerdFonts/FiraMono/FiraMonoNerdFont-Bold.otf:0
          Features: ()
Paths:
  kitty: /nix/store/v4aw3pblfy9rljnpbjm9s970cdr7cszn-kitty-0.43.1/bin/kitty
  base dir: /nix/store/v4aw3pblfy9rljnpbjm9s970cdr7cszn-kitty-0.43.1/lib/kitty
  extensions dir: /nix/store/v4aw3pblfy9rljnpbjm9s970cdr7cszn-kitty-0.43.1/lib/kitty/kitty
  system shell: /run/current-system/sw/bin/nu
System color scheme: light. Applied color theme type: none
Loaded config files:
  /home/syk/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity    0.5
cursor_blink_interval (0.0, kitty.options.utils.EasingFunction(), kitty.options.utils.EasingFunction())
disable_ligatures     1

Important environment variables seen by the kitty process:
	PATH                                /run/wrappers/bin:/home/syk/.nix-profile/bin:/nix/profile/bin:/home/syk/.local/state/nix/profile/bin:/etc/profiles/per-user/syk/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/nix/store/v4aw3pblfy9rljnpbjm9s970cdr7cszn-kitty-0.43.1/bin:/nix/store/xvrvpcj3rw3fdv7chhxl39abip0mm8rj-imagemagick-7.1.2-3/bin:/nix/store/rz4bmcm8dwsy7ylx6rhffkwkqn6n8srn-ncurses-6.5-dev/bin
	LANG                                zh_CN.UTF-8
	EDITOR                              hx
	SHELL                               /run/current-system/sw/bin/nu
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                syk
	XDG_CONFIG_DIRS                     /nix/store/phrjn3rincxmnxssghql9fj64212v879-kglobalacceld-6.4.5/etc/xdg:/nix/store/phrjn3rincxmnxssghql9fj64212v879-kglobalacceld-6.4.5/etc/xdg:/home/syk/.config/kdedefaults:/nix/store/pr9yb0y4mzfwvjj54qfyyngdyjbi756r-plasma-workspace-6.4.5/etc/xdg:/nix/store/phrjn3rincxmnxssghql9fj64212v879-kglobalacceld-6.4.5/etc/xdg:/nix/store/mkr9waxs5d8l4zx757mm872fa96i1ymj-baloo-6.18.0/etc/xdg:/home/syk/.config/kdedefaults:/etc/xdg:/home/syk/.nix-profile/etc/xdg:/nix/profile/etc/xdg:/home/syk/.local/state/nix/profile/etc/xdg:/etc/profiles/per-user/syk/etc/xdg:/nix/var/nix/profiles/default/etc/xdg:/run/current-system/sw/etc/xdg
	XDG_DATA_DIRS                       /nix/store/1y1ml5ykxp1kv2855252m0yx04pl3dhc-kwin-6.4.5/share:/nix/store/llrpphf9znqy18z75zsxrgjs1am61bqk-kscreenlocker-6.4.5/share:/nix/store/pqlf1y7v6skl2pjvbv3myf8i08wfgjl4-libplasma-6.4.5/share:/nix/store/4l566w232gvvmgmmdmfhgmmvmfdq7liq-kparts-6.18.0/share:/nix/store/1znzgjr42kzbgs7c7c53kh8kic1x8ad4-libkscreen-6.4.5/share:/nix/store/sp2cxs6r4v6sg8z4w5j3swmsa7l7swf6-kpipewire-6.4.5/share:/nix/store/jbw9gfbgmizb2q7zid5h1bdbafbmjl20-kdeclarative-6.18.0/share:/nix/store/gg0i9az2nrcb1vix1v1jf1vjim4iw1db-breeze-6.4.5/share:/nix/store/vhbqrrd64xr62bxpnqxh85s2il664285-kdecoration-6.4.5/share:/nix/store/h6hff1f6a16fd1mkq5sbf33zvayb7r2y-frameworkintegration-6.18.0/share:/nix/store/ffdqg4fpw3y7dsmzjalhb0d65ds9fq1l-oxygen-icons-6.1.0/share:/nix/store/hzhw7sj0mji8jk3xdpkj3p8kzd90cb2k-knewstuff-6.18.0/share:/nix/store/hssa6hqw8pir2s0r28i8hwmg44wgqy0q-kcmutils-6.18.0/share:/nix/store/8585n5brl833hfdi5jsfv9mf9hn6jsnr-kxmlgui-6.18.0/share:/nix/store/3kv4ipg44v3fb0zjxap668jlwbhjk5pb-ktextwidgets-6.18.0/share:/nix/store/prahd91j0sl8gqy65b45w1n1qn7380q4-kglobalaccel-6.18.0/share:/nix/store/rxxpv49mm1fvacn9jp42pz3nrv4ncl7l-kpackage-6.18.0/share:/nix/store/0m3lmwjsw7mhh9vhywkb2bgylp77dz6k-qqc2-desktop-style-6.18.0/share:/nix/store/aqjwpc0jinff9wmvh51mm2qldnjj4qrp-sonnet-6.18.0/share:/nix/store/dmhzijn8zbn46czph0a11apn637mg6ji-kirigami-6.18.0/share:/nix/store/5cl4m1kz0jyhf4ji06qd93awsqk4dg9y-kio-6.18.0/share:/nix/store/6y4615v96l2kz76j8ghc0a0dgwvmf16q-solid-6.18.0/share:/nix/store/a93cjg4hmydcic50nfkimha58x0bd7lp-kwallet-6.18.0/share:/nix/store/10ahhmqpbmy6rpznpjjadwz8c722a256-libgpg-error-1.55/share:/nix/store/jncfjwgqaihd9dbr4xgy0lx0xj9sa1ln-kservice-6.18.0/share:/nix/store/a5s3gh336wq7kirx4rdmn9vxwdqglgsx-kjobwidgets-6.18.0/share:/nix/store/9sxafh2xbhd9krwvkv4zm9yqs46wsmn5-knotifications-6.18.0/share:/nix/store/kb21jwqcs5zvwyy6ksbi7wn9v7brlgph-kitemviews-6.18.0/share:/nix/store/y800ak1s4mypwx6wqyb09qrhrvn35sl7-kdoctools-6.18.0/share:/nix/store/6054l6irwx2acnkvcsywrm3nccb5kk2z-kdbusaddons-6.18.0/share:/nix/store/jfahq2mm265vyhmnj18q6asqfv8y2hh4-kcompletion-6.18.0/share:/nix/store/kyd9spnvs3f7zfabp1njn6339gx486jc-kbookmarks-6.18.0/share:/nix/store/9sv28aic81qn206sq2q62n4i1byxjd8q-kauth-6.18.0/share:/nix/store/71bn92fqwbjfz78sf6f98l4dwlp3im84-kiconthemes-6.18.0/share:/nix/store/jd0zas3cyb5plmk6xlcipb2wlsgwbq8f-karchive-6.18.0/share:/nix/store/37cmxs3j51kcfgf6sy7q3l65q5l75sl7-breeze-icons-6.18.0/share:/nix/store/y2x1phfyzp64j8ib986n36qd14gz3qy7-kconfigwidgets-6.18.0/share:/nix/store/xfyzyxlmq62wjwp23m4z9icb6m7nk41c-kwidgetsaddons-6.18.0/share:/nix/store/pf1y9crw19rs2w0ykwg240xz0pxad2ss-kcodecs-6.18.0/share:/nix/store/wpvqcn869dwdvmb9b0b9mfnkkhm4yzxr-kcolorscheme-6.18.0/share:/nix/store/7bzdfn3vwdw8pzdba9f32s9blxq015dn-appstream-qt-1.0.4/share:/nix/store/2b8277rf1k9rl7sf1zmhjkv1nclg2cid-pipewire-1.4.7/share:/nix/store/ks6y6yq4pmqki57jfhyk81kx1mkz740s-kwindowsystem-6.18.0/share:/nix/store/82rz8ggg9p6jwlbblnqp1cxgazm78ijn-ki18n-6.18.0/share:/nix/store/16wipa83s4l3q9qiahvd4cf2hlgc2z70-kcoreaddons-6.18.0/share:/nix/store/6lih8lbx9l6sa0rygqjviq7pgr3jld5f-kconfig-6.18.0/share:/nix/store/pn25cyqh25nj37raz3agbavlsvkl5xc6-hunspell-1.7.2/share:/nix/store/dccakk1342p30zyk01viwinsnnpb9qcb-cups-2.4.12/share:/nix/store/zkpfddh7v4svk76afsc1bbbvqapzjpir-cups-2.4.12-lib/share:/nix/store/kld68jc4zmliifsvhq8gwrn85zxr8vr4-fontconfig-2.16.2-lib/share:/nix/store/baz6ga44p6b759mq2cc83xg58ngvh0jr-util-linux-2.41.1-lib/share:/nix/store/acjdidq41qig9khxcm7gx1d7brzjs249-systemd-257.8/share:/nix/store/qfm3kqdbpd289nnmdhd4dis4svd2nzwv-glib-2.84.4/share:/nix/store/b2jdp6hfygj6mxndszl0yyczprm1h8b3-gettext-0.25.1/share:/nix/store/1y1ml5ykxp1kv2855252m0yx04pl3dhc-kwin-6.4.5/share:/nix/store/llrpphf9znqy18z75zsxrgjs1am61bqk-kscreenlocker-6.4.5/share:/nix/store/pqlf1y7v6skl2pjvbv3myf8i08wfgjl4-libplasma-6.4.5/share:/nix/store/4l566w232gvvmgmmdmfhgmmvmfdq7liq-kparts-6.18.0/share:/nix/store/1znzgjr42kzbgs7c7c53kh8kic1x8ad4-libkscreen-6.4.5/share:/nix/store/sp2cxs6r4v6sg8z4w5j3swmsa7l7swf6-kpipewire-6.4.5/share:/nix/store/jbw9gfbgmizb2q7zid5h1bdbafbmjl20-kdeclarative-6.18.0/share:/nix/store/gg0i9az2nrcb1vix1v1jf1vjim4iw1db-breeze-6.4.5/share:/nix/store/vhbqrrd64xr62bxpnqxh85s2il664285-kdecoration-6.4.5/share:/nix/store/h6hff1f6a16fd1mkq5sbf33zvayb7r2y-frameworkintegration-6.18.0/share:/nix/store/ffdqg4fpw3y7dsmzjalhb0d65ds9fq1l-oxygen-icons-6.1.0/share:/nix/store/hzhw7sj0mji8jk3xdpkj3p8kzd90cb2k-knewstuff-6.18.0/share:/nix/store/hssa6hqw8pir2s0r28i8hwmg44wgqy0q-kcmutils-6.18.0/share:/nix/store/8585n5brl833hfdi5jsfv9mf9hn6jsnr-kxmlgui-6.18.0/share:/nix/store/3kv4ipg44v3fb0zjxap668jlwbhjk5pb-ktextwidgets-6.18.0/share:/nix/store/prahd91j0sl8gqy65b45w1n1qn7380q4-kglobalaccel-6.18.0/share:/nix/store/rxxpv49mm1fvacn9jp42pz3nrv4ncl7l-kpackage-6.18.0/share:/nix/store/0m3lmwjsw7mhh9vhywkb2bgylp77dz6k-qqc2-desktop-style-6.18.0/share:/nix/store/aqjwpc0jinff9wmvh51mm2qldnjj4qrp-sonnet-6.18.0/share:/nix/store/dmhzijn8zbn46czph0a11apn637mg6ji-kirigami-6.18.0/share:/nix/store/5cl4m1kz0jyhf4ji06qd93awsqk4dg9y-kio-6.18.0/share:/nix/store/6y4615v96l2kz76j8ghc0a0dgwvmf16q-solid-6.18.0/share:/nix/store/a93cjg4hmydcic50nfkimha58x0bd7lp-kwallet-6.18.0/share:/nix/store/10ahhmqpbmy6rpznpjjadwz8c722a256-libgpg-error-1.55/share:/nix/store/jncfjwgqaihd9dbr4xgy0lx0xj9sa1ln-kservice-6.18.0/share:/nix/store/a5s3gh336wq7kirx4rdmn9vxwdqglgsx-kjobwidgets-6.18.0/share:/nix/store/9sxafh2xbhd9krwvkv4zm9yqs46wsmn5-knotifications-6.18.0/share:/nix/store/kb21jwqcs5zvwyy6ksbi7wn9v7brlgph-kitemviews-6.18.0/share:/nix/store/y800ak1s4mypwx6wqyb09qrhrvn35sl7-kdoctools-6.18.0/share:/nix/store/6054l6irwx2acnkvcsywrm3nccb5kk2z-kdbusaddons-6.18.0/share:/nix/store/jfahq2mm265vyhmnj18q6asqfv8y2hh4-kcompletion-6.18.0/share:/nix/store/kyd9spnvs3f7zfabp1njn6339gx486jc-kbookmarks-6.18.0/share:/nix/store/9sv28aic81qn206sq2q62n4i1byxjd8q-kauth-6.18.0/share:/nix/store/71bn92fqwbjfz78sf6f98l4dwlp3im84-kiconthemes-6.18.0/share:/nix/store/jd0zas3cyb5plmk6xlcipb2wlsgwbq8f-karchive-6.18.0/share:/nix/store/37cmxs3j51kcfgf6sy7q3l65q5l75sl7-breeze-icons-6.18.0/share:/nix/store/y2x1phfyzp64j8ib986n36qd14gz3qy7-kconfigwidgets-6.18.0/share:/nix/store/xfyzyxlmq62wjwp23m4z9icb6m7nk41c-kwidgetsaddons-6.18.0/share:/nix/store/pf1y9crw19rs2w0ykwg240xz0pxad2ss-kcodecs-6.18.0/share:/nix/store/wpvqcn869dwdvmb9b0b9mfnkkhm4yzxr-kcolorscheme-6.18.0/share:/nix/store/7bzdfn3vwdw8pzdba9f32s9blxq015dn-appstream-qt-1.0.4/share:/nix/store/2b8277rf1k9rl7sf1zmhjkv1nclg2cid-pipewire-1.4.7/share:/nix/store/ks6y6yq4pmqki57jfhyk81kx1mkz740s-kwindowsystem-6.18.0/share:/nix/store/82rz8ggg9p6jwlbblnqp1cxgazm78ijn-ki18n-6.18.0/share:/nix/store/16wipa83s4l3q9qiahvd4cf2hlgc2z70-kcoreaddons-6.18.0/share:/nix/store/6lih8lbx9l6sa0rygqjviq7pgr3jld5f-kconfig-6.18.0/share:/nix/store/pn25cyqh25nj37raz3agbavlsvkl5xc6-hunspell-1.7.2/share:/nix/store/dccakk1342p30zyk01viwinsnnpb9qcb-cups-2.4.12/share:/nix/store/zkpfddh7v4svk76afsc1bbbvqapzjpir-cups-2.4.12-lib/share:/nix/store/kld68jc4zmliifsvhq8gwrn85zxr8vr4-fontconfig-2.16.2-lib/share:/nix/store/baz6ga44p6b759mq2cc83xg58ngvh0jr-util-linux-2.41.1-lib/share:/nix/store/acjdidq41qig9khxcm7gx1d7brzjs249-systemd-257.8/share:/nix/store/qfm3kqdbpd289nnmdhd4dis4svd2nzwv-glib-2.84.4/share:/nix/store/b2jdp6hfygj6mxndszl0yyczprm1h8b3-gettext-0.25.1/share:/nix/store/pr9yb0y4mzfwvjj54qfyyngdyjbi756r-plasma-workspace-6.4.5/share:/nix/store/6xmy25hpdvjngwzm4ch4vnyld1aiicm6-plasma5support-6.4.5/share:/nix/store/rgfdj04cvfs8css4mmq6zlsbd0nnxzz0-networkmanager-1.52.1/share:/nix/store/a55chb1mj39mgjcbw0h655ri6dlgd0wl-gnutls-3.8.10/share:/nix/store/jf0yg1cyin0an00h1glrjx3lc0wyknr7-plasma-nano-6.4.5/share:/nix/store/9mp6zg5g2i26s8yz9cl3c25pynbga1rm-milou-6.4.5/share:/nix/store/v25yi2bxn0bxavndxn95mxs9sqba686l-libksysguard-6.4.5/share:/nix/store/1y1ml5ykxp1kv2855252m0yx04pl3dhc-kwin-6.4.5/share:/nix/store/sp2cxs6r4v6sg8z4w5j3swmsa7l7swf6-kpipewire-6.4.5/share:/nix/store/gg0i9az2nrcb1vix1v1jf1vjim4iw1db-breeze-6.4.5/share:/nix/store/vhbqrrd64xr62bxpnqxh85s2il664285-kdecoration-6.4.5/share:/nix/store/h6hff1f6a16fd1mkq5sbf33zvayb7r2y-frameworkintegration-6.18.0/share:/nix/store/ffdqg4fpw3y7dsmzjalhb0d65ds9fq1l-oxygen-icons-6.1.0/share:/nix/store/cjnaknqxmzsqy76yy5w9wpavhkbchknh-kuserfeedback-6.18.0/share:/nix/store/5l818zxaz1rc4y94nkx9yli3s3yld1sk-kunitconversion-6.18.0/share:/nix/store/jh4vsy1l9nxz2c3930a87x86p62fwhfr-ktexteditor-6.18.0/share:/nix/store/vxvyhhq4g6fl451vpl6p0yvavh6hay57-kstatusnotifieritem-6.18.0/share:/nix/store/llrpphf9znqy18z75zsxrgjs1am61bqk-kscreenlocker-6.4.5/share:/nix/store/pqlf1y7v6skl2pjvbv3myf8i08wfgjl4-libplasma-6.4.5/share:/nix/store/1znzgjr42kzbgs7c7c53kh8kic1x8ad4-libkscreen-6.4.5/share:/nix/store/4l566w232gvvmgmmdmfhgmmvmfdq7liq-kparts-6.18.0/share:/nix/store/v06ny4j28cbriajvr6zvlyppczlpr5rj-knotifyconfig-6.18.0/share:/nix/store/hzhw7sj0mji8jk3xdpkj3p8kzd90cb2k-knewstuff-6.18.0/share:/nix/store/rxxpv49mm1fvacn9jp42pz3nrv4ncl7l-kpackage-6.18.0/share:/nix/store/c8sjz0gb5idwakaxjn3cl9c0vinycl07-kirigami-addons-1.9.0/share:/nix/store/5c19xqsx7lfgrmg57xzx7hcxpjvyjb9x-kio-extras-25.08.1/share:/nix/store/jf62lj68sz0dj8bz3s48w1d52rcd5ysy-syntax-highlighting-6.18.0/share:/nix/store/x3psn3n9y7x1jf3hmdckbjqqdp4zs13w-phonon-4.12.0/share:/nix/store/yjr16xgx7l98vasaji4r7v22nwik67lx-kdnssd-6.18.0/share:/nix/store/s9llbgh2lmnppy41m4gcw4mym6di22ci-kholidays-6.18.0/share:/nix/store/rqjxpmgqn8jib6r6yrxdah4ai3bxhivi-kdesu-6.18.0/share:/nix/store/hc3p3dwqgx8i70ciyzlmz6qfpzbij59l-kpty-6.18.0/share:/nix/store/jbw9gfbgmizb2q7zid5h1bdbafbmjl20-kdeclarative-6.18.0/share:/nix/store/hssa6hqw8pir2s0r28i8hwmg44wgqy0q-kcmutils-6.18.0/share:/nix/store/8znak9isqv40fv87gka0issxf7q922hf-kactivitymanagerd-6.4.5/share:/nix/store/8585n5brl833hfdi5jsfv9mf9hn6jsnr-kxmlgui-6.18.0/share:/nix/store/3kv4ipg44v3fb0zjxap668jlwbhjk5pb-ktextwidgets-6.18.0/share:/nix/store/prahd91j0sl8gqy65b45w1n1qn7380q4-kglobalaccel-6.18.0/share:/nix/store/y2x1phfyzp64j8ib986n36qd14gz3qy7-kconfigwidgets-6.18.0/share:/nix/store/mkr9waxs5d8l4zx757mm872fa96i1ymj-baloo-6.18.0/share:/nix/store/5cl4m1kz0jyhf4ji06qd93awsqk4dg9y-kio-6.18.0/share:/nix/store/6y4615v96l2kz76j8ghc0a0dgwvmf16q-solid-6.18.0/share:/nix/store/a93cjg4hmydcic50nfkimha58x0bd7lp-kwallet-6.18.0/share:/nix/store/10ahhmqpbmy6rpznpjjadwz8c722a256-libgpg-error-1.55/share:/nix/store/jncfjwgqaihd9dbr4xgy0lx0xj9sa1ln-kservice-6.18.0/share:/nix/store/a5s3gh336wq7kirx4rdmn9vxwdqglgsx-kjobwidgets-6.18.0/share:/nix/store/9sxafh2xbhd9krwvkv4zm9yqs46wsmn5-knotifications-6.18.0/share:/nix/store/kb21jwqcs5zvwyy6ksbi7wn9v7brlgph-kitemviews-6.18.0/share:/nix/store/y800ak1s4mypwx6wqyb09qrhrvn35sl7-kdoctools-6.18.0/share:/nix/store/jfahq2mm265vyhmnj18q6asqfv8y2hh4-kcompletion-6.18.0/share:/nix/store/kyd9spnvs3f7zfabp1njn6339gx486jc-kbookmarks-6.18.0/share:/nix/store/9sv28aic81qn206sq2q62n4i1byxjd8q-kauth-6.18.0/share:/nix/store/ks6y6yq4pmqki57jfhyk81kx1mkz740s-kwindowsystem-6.18.0/share:/nix/store/arwr0528786i713nqm52p0kxhf62wpfs-kfilemetadata-6.18.0/share:/nix/store/wwqyxsvmg41q5ckfvvv6wa50nwvz9dv4-libidn2-2.3.8/share:/nix/store/6054l6irwx2acnkvcsywrm3nccb5kk2z-kdbusaddons-6.18.0/share:/nix/store/7bzdfn3vwdw8pzdba9f32s9blxq015dn-appstream-qt-1.0.4/share:/nix/store/2b8277rf1k9rl7sf1zmhjkv1nclg2cid-pipewire-1.4.7/share:/nix/store/cwj1fnp2z9h0dg8kxbm9xhm7psyr8vbf-libqalculate-5.7.0/share:/nix/store/0m3lmwjsw7mhh9vhywkb2bgylp77dz6k-qqc2-desktop-style-6.18.0/share:/nix/store/aqjwpc0jinff9wmvh51mm2qldnjj4qrp-sonnet-6.18.0/share:/nix/store/dmhzijn8zbn46czph0a11apn637mg6ji-kirigami-6.18.0/share:/nix/store/71bn92fqwbjfz78sf6f98l4dwlp3im84-kiconthemes-6.18.0/share:/nix/store/xfyzyxlmq62wjwp23m4z9icb6m7nk41c-kwidgetsaddons-6.18.0/share:/nix/store/jd0zas3cyb5plmk6xlcipb2wlsgwbq8f-karchive-6.18.0/share:/nix/store/37cmxs3j51kcfgf6sy7q3l65q5l75sl7-breeze-icons-6.18.0/share:/nix/store/16wipa83s4l3q9qiahvd4cf2hlgc2z70-kcoreaddons-6.18.0/share:/nix/store/wpvqcn869dwdvmb9b0b9mfnkkhm4yzxr-kcolorscheme-6.18.0/share:/nix/store/82rz8ggg9p6jwlbblnqp1cxgazm78ijn-ki18n-6.18.0/share:/nix/store/6lih8lbx9l6sa0rygqjviq7pgr3jld5f-kconfig-6.18.0/share:/nix/store/pf1y9crw19rs2w0ykwg240xz0pxad2ss-kcodecs-6.18.0/share:/nix/store/dccakk1342p30zyk01viwinsnnpb9qcb-cups-2.4.12/share:/nix/store/zkpfddh7v4svk76afsc1bbbvqapzjpir-cups-2.4.12-lib/share:/nix/store/kld68jc4zmliifsvhq8gwrn85zxr8vr4-fontconfig-2.16.2-lib/share:/nix/store/baz6ga44p6b759mq2cc83xg58ngvh0jr-util-linux-2.41.1-lib/share:/nix/store/acjdidq41qig9khxcm7gx1d7brzjs249-systemd-257.8/share:/nix/store/qfm3kqdbpd289nnmdhd4dis4svd2nzwv-glib-2.84.4/share:/nix/store/b2jdp6hfygj6mxndszl0yyczprm1h8b3-gettext-0.25.1/share:/nix/store/zbzjxl5ryd9z6yn3dkrgr11n3lrnmni0-desktops/share:/home/syk/.nix-profile/share:/nix/profile/share:/home/syk/.local/state/nix/profile/share:/etc/profiles/per-user/syk/share:/nix/var/nix/profiles/default/share:/run/current-system/sw/share
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_CURRENT_DESKTOP                 KDE
	XDG_MENU_PREFIX                     plasma-
	XDG_SEAT                            seat0
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 KDE
	XDG_SESSION_ID                      2
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session1
	XDG_SESSION_TYPE                    wayland
	XDG_VTNR                            2

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.
`background_opacity 0.5`

**Comment by kovidgoyal** [comment]
Does not reproduce for me, running from master, probably was fixed by
the fix for #9060 so try the nightly build.

**Comment by SaltyKitkat** [comment]
Thanks. Looking forward to the new release :)

**Comment by kovidgoyal** [comment]
You dont need to wait use the nightly build.

**Comment by keynslug** [comment]
I can still reproduce on Nightly (c40ff9439). No `background-opacity`, `cursor_stop_blinking_after` is just 0.1.

Compared to 0.42.2, 0.43.1 constantly runs something each frame across the Wayland socket. Here's a snippet of activity captured with [wayland-debug](https://github.com/wmww/wayland-debug), 300 milliseconds starting 2 seconds since `kitty` startup. On 0.42.2 there's no such activity.

```
 2.0128 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dk.destroyed after 0.0163s ↲
 2.0128 A: wl_callback@47dk.done(callback_data=37631245) ↲
 2.0130 A: wl_callback@44dv.done(callback_data=40315) ↲
 2.0130 A: wl_buffer@45b.release() ↲
 2.0131 A: → wl_surface@33a.attach(buffer=wl_buffer@45b, x=0, y=0)
 2.0132 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.0132 A: → wl_surface@33a.commit()
 2.0132 A: → wl_display@1a.sync(callback=new wl_callback@44dw)
 2.0132 A: → wl_surface@33a.frame(callback=new wl_callback@47dl)
 2.0132 A: → wl_surface@33a.commit()
 2.0134 A: wl_display@1a.delete_id(id=44) -- wl_callback@44dw.destroyed after 0.0002s ↲
 2.0294 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dl.destroyed after 0.0163s ↲
 2.0295 A: wl_callback@47dl.done(callback_data=37631262) ↲
 2.0296 A: wl_callback@44dw.done(callback_data=40315) ↲
 2.0296 A: wl_buffer@43c.release() ↲
 2.0297 A: → wl_surface@33a.attach(buffer=wl_buffer@43c, x=0, y=0)
 2.0297 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.0297 A: → wl_surface@33a.commit()
 2.0297 A: → wl_display@1a.sync(callback=new wl_callback@44dx)
 2.0298 A: → wl_surface@33a.frame(callback=new wl_callback@47dm)
 2.0298 A: → wl_surface@33a.commit()
 2.0299 A: wl_display@1a.delete_id(id=44) -- wl_callback@44dx.destroyed after 0.0002s ↲
 2.0461 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dm.destroyed after 0.0163s ↲
 2.0461 A: wl_callback@47dm.done(callback_data=37631279) ↲
 2.0462 A: wl_callback@44dx.done(callback_data=40315) ↲
 2.0462 A: wl_buffer@45b.release() ↲
 2.0464 A: → wl_surface@33a.attach(buffer=wl_buffer@45b, x=0, y=0)
 2.0464 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.0464 A: → wl_surface@33a.commit()
 2.0464 A: → wl_display@1a.sync(callback=new wl_callback@44dy)
 2.0464 A: → wl_surface@33a.frame(callback=new wl_callback@47dn)
 2.0464 A: → wl_surface@33a.commit()
 2.0466 A: wl_display@1a.delete_id(id=44) -- wl_callback@44dy.destroyed after 0.0002s ↲
 2.0623 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dn.destroyed after 0.0159s ↲
 2.0623 A: wl_callback@47dn.done(callback_data=37631295) ↲
 2.0623 A: wl_callback@44dy.done(callback_data=40315) ↲
 2.0623 A: wl_buffer@43c.release() ↲
 2.0624 A: → wl_surface@33a.attach(buffer=wl_buffer@43c, x=0, y=0)
 2.0624 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.0624 A: → wl_surface@33a.commit()
 2.0624 A: → wl_display@1a.sync(callback=new wl_callback@44dz)
 2.0624 A: → wl_surface@33a.frame(callback=new wl_callback@47do)
 2.0624 A: → wl_surface@33a.commit()
 2.0625 A: wl_display@1a.delete_id(id=44) -- wl_callback@44dz.destroyed after 0.0001s ↲
 2.0796 A: wl_display@1a.delete_id(id=47) -- wl_callback@47do.destroyed after 0.0172s ↲
 2.0796 A: wl_callback@47do.done(callback_data=37631312) ↲
 2.0798 A: wl_callback@44dz.done(callback_data=40315) ↲
 2.0798 A: wl_buffer@45b.release() ↲
 2.0800 A: → wl_surface@33a.attach(buffer=wl_buffer@45b, x=0, y=0)
 2.0800 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.0800 A: → wl_surface@33a.commit()
 2.0800 A: → wl_display@1a.sync(callback=new wl_callback@44ea)
 2.0800 A: → wl_surface@33a.frame(callback=new wl_callback@47dp)
 2.0800 A: → wl_surface@33a.commit()
 2.0802 A: wl_display@1a.delete_id(id=44) -- wl_callback@44ea.destroyed after 0.0002s ↲
 2.0967 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dp.destroyed after 0.0167s ↲
 2.0967 A: wl_callback@47dp.done(callback_data=37631329) ↲
 2.0969 A: wl_callback@44ea.done(callback_data=40315) ↲
 2.0969 A: wl_buffer@43c.release() ↲
 2.0972 A: → wl_surface@33a.attach(buffer=wl_buffer@43c, x=0, y=0)
 2.0972 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.0972 A: → wl_surface@33a.commit()
 2.0972 A: → wl_display@1a.sync(callback=new wl_callback@44eb)
 2.0972 A: → wl_surface@33a.frame(callback=new wl_callback@47dq)
 2.0972 A: → wl_surface@33a.commit()
 2.0974 A: wl_display@1a.delete_id(id=44) -- wl_callback@44eb.destroyed after 0.0002s ↲
 2.1128 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dq.destroyed after 0.0156s ↲
 2.1128 A: wl_callback@47dq.done(callback_data=37631345) ↲
 2.1130 A: wl_callback@44eb.done(callback_data=40315) ↲
 2.1130 A: wl_buffer@45b.release() ↲
 2.1131 A: → wl_surface@33a.attach(buffer=wl_buffer@45b, x=0, y=0)
 2.1132 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.1132 A: → wl_surface@33a.commit()
 2.1132 A: → wl_display@1a.sync(callback=new wl_callback@44ec)
 2.1132 A: → wl_surface@33a.frame(callback=new wl_callback@47dr)
 2.1132 A: → wl_surface@33a.commit()
 2.1134 A: wl_display@1a.delete_id(id=44) -- wl_callback@44ec.destroyed after 0.0002s ↲
 2.1296 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dr.destroyed after 0.0164s ↲
 2.1296 A: wl_callback@47dr.done(callback_data=37631362) ↲
 2.1298 A: wl_callback@44ec.done(callback_data=40315) ↲
 2.1298 A: wl_buffer@43c.release() ↲
 2.1300 A: → wl_surface@33a.attach(buffer=wl_buffer@43c, x=0, y=0)
 2.1300 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.1300 A: → wl_surface@33a.commit()
 2.1300 A: → wl_display@1a.sync(callback=new wl_callback@44ed)
 2.1300 A: → wl_surface@33a.frame(callback=new wl_callback@47ds)
 2.1300 A: → wl_surface@33a.commit()
 2.1302 A: wl_display@1a.delete_id(id=44) -- wl_callback@44ed.destroyed after 0.0002s ↲
 2.1465 A: wl_display@1a.delete_id(id=47) -- wl_callback@47ds.destroyed after 0.0165s ↲
 2.1465 A: wl_callback@47ds.done(callback_data=37631379) ↲
 2.1467 A: wl_callback@44ed.done(callback_data=40315) ↲
 2.1467 A: wl_buffer@45b.release() ↲
 2.1469 A: → wl_surface@33a.attach(buffer=wl_buffer@45b, x=0, y=0)
 2.1469 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.1469 A: → wl_surface@33a.commit()
 2.1469 A: → wl_display@1a.sync(callback=new wl_callback@44ee)
 2.1469 A: → wl_surface@33a.frame(callback=new wl_callback@47dt)
 2.1469 A: → wl_surface@33a.commit()
 2.1471 A: wl_display@1a.delete_id(id=44) -- wl_callback@44ee.destroyed after 0.0002s ↲
 2.1632 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dt.destroyed after 0.0163s ↲
 2.1632 A: wl_callback@47dt.done(callback_data=37631396) ↲
 2.1634 A: wl_callback@44ee.done(callback_data=40315) ↲
 2.1634 A: wl_buffer@43c.release() ↲
 2.1636 A: → wl_surface@33a.attach(buffer=wl_buffer@43c, x=0, y=0)
 2.1637 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.1637 A: → wl_surface@33a.commit()
 2.1637 A: → wl_display@1a.sync(callback=new wl_callback@44ef)
 2.1637 A: → wl_surface@33a.frame(callback=new wl_callback@47du)
 2.1637 A: → wl_surface@33a.commit()
 2.1639 A: wl_display@1a.delete_id(id=44) -- wl_callback@44ef.destroyed after 0.0002s ↲
 2.1795 A: wl_display@1a.delete_id(id=47) -- wl_callback@47du.destroyed after 0.0158s ↲
 2.1795 A: wl_callback@47du.done(callback_data=37631412) ↲
 2.1796 A: wl_callback@44ef.done(callback_data=40315) ↲
 2.1797 A: wl_buffer@45b.release() ↲
 2.1798 A: → wl_surface@33a.attach(buffer=wl_buffer@45b, x=0, y=0)
 2.1798 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.1799 A: → wl_surface@33a.commit()
 2.1799 A: → wl_display@1a.sync(callback=new wl_callback@44eg)
 2.1799 A: → wl_surface@33a.frame(callback=new wl_callback@47dv)
 2.1799 A: → wl_surface@33a.commit()
 2.1800 A: wl_display@1a.delete_id(id=44) -- wl_callback@44eg.destroyed after 0.0002s ↲
 2.1963 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dv.destroyed after 0.0164s ↲
 2.1963 A: wl_callback@47dv.done(callback_data=37631429) ↲
 2.1964 A: wl_callback@44eg.done(callback_data=40315) ↲
 2.1964 A: wl_buffer@43c.release() ↲
 2.1967 A: → wl_surface@33a.attach(buffer=wl_buffer@43c, x=0, y=0)
 2.1967 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.1967 A: → wl_surface@33a.commit()
 2.1967 A: → wl_display@1a.sync(callback=new wl_callback@44eh)
 2.1967 A: → wl_surface@33a.frame(callback=new wl_callback@47dw)
 2.1967 A: → wl_surface@33a.commit()
 2.1969 A: wl_display@1a.delete_id(id=44) -- wl_callback@44eh.destroyed after 0.0002s ↲
 2.2128 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dw.destroyed after 0.0161s ↲
 2.2129 A: wl_callback@47dw.done(callback_data=37631445) ↲
 2.2130 A: wl_callback@44eh.done(callback_data=40315) ↲
 2.2130 A: wl_buffer@45b.release() ↲
 2.2132 A: → wl_surface@33a.attach(buffer=wl_buffer@45b, x=0, y=0)
 2.2132 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.2132 A: → wl_surface@33a.commit()
 2.2132 A: → wl_display@1a.sync(callback=new wl_callback@44ei)
 2.2132 A: → wl_surface@33a.frame(callback=new wl_callback@47dx)
 2.2132 A: → wl_surface@33a.commit()
 2.2134 A: wl_display@1a.delete_id(id=44) -- wl_callback@44ei.destroyed after 0.0002s ↲
 2.2295 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dx.destroyed after 0.0163s ↲
 2.2296 A: wl_callback@47dx.done(callback_data=37631462) ↲
 2.2297 A: wl_callback@44ei.done(callback_data=40315) ↲
 2.2297 A: wl_buffer@43c.release() ↲
 2.2298 A: → wl_surface@33a.attach(buffer=wl_buffer@43c, x=0, y=0)
 2.2298 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.2299 A: → wl_surface@33a.commit()
 2.2299 A: → wl_display@1a.sync(callback=new wl_callback@44ej)
 2.2299 A: → wl_surface@33a.frame(callback=new wl_callback@47dy)
 2.2299 A: → wl_surface@33a.commit()
 2.2300 A: wl_display@1a.delete_id(id=44) -- wl_callback@44ej.destroyed after 0.0002s ↲
 2.2461 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dy.destroyed after 0.0162s ↲
 2.2461 A: wl_callback@47dy.done(callback_data=37631479) ↲
 2.2462 A: wl_callback@44ej.done(callback_data=40315) ↲
 2.2462 A: wl_buffer@45b.release() ↲
 2.2464 A: → wl_surface@33a.attach(buffer=wl_buffer@45b, x=0, y=0)
 2.2464 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.2464 A: → wl_surface@33a.commit()
 2.2464 A: → wl_display@1a.sync(callback=new wl_callback@44ek)
 2.2464 A: → wl_surface@33a.frame(callback=new wl_callback@47dz)
 2.2464 A: → wl_surface@33a.commit()
 2.2466 A: wl_display@1a.delete_id(id=44) -- wl_callback@44ek.destroyed after 0.0002s ↲
 2.2629 A: wl_display@1a.delete_id(id=47) -- wl_callback@47dz.destroyed after 0.0164s ↲
 2.2629 A: wl_callback@47dz.done(callback_data=37631495) ↲
 2.2630 A: wl_callback@44ek.done(callback_data=40315) ↲
 2.2630 A: wl_buffer@43c.release() ↲
 2.2632 A: → wl_surface@33a.attach(buffer=wl_buffer@43c, x=0, y=0)
 2.2632 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.2632 A: → wl_surface@33a.commit()
 2.2632 A: → wl_display@1a.sync(callback=new wl_callback@44el)
 2.2632 A: → wl_surface@33a.frame(callback=new wl_callback@47ea)
 2.2632 A: → wl_surface@33a.commit()
 2.2634 A: wl_display@1a.delete_id(id=44) -- wl_callback@44el.destroyed after 0.0002s ↲
 2.2799 A: wl_display@1a.delete_id(id=47) -- wl_callback@47ea.destroyed after 0.0167s ↲
 2.2799 A: wl_callback@47ea.done(callback_data=37631512) ↲
 2.2801 A: wl_callback@44el.done(callback_data=40315) ↲
 2.2801 A: wl_buffer@45b.release() ↲
 2.2803 A: → wl_surface@33a.attach(buffer=wl_buffer@45b, x=0, y=0)
 2.2803 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.2803 A: → wl_surface@33a.commit()
 2.2803 A: → wl_display@1a.sync(callback=new wl_callback@44em)
 2.2804 A: → wl_surface@33a.frame(callback=new wl_callback@47eb)
 2.2804 A: → wl_surface@33a.commit()
 2.2805 A: wl_display@1a.delete_id(id=44) -- wl_callback@44em.destroyed after 0.0002s ↲
 2.2981 A: wl_display@1a.delete_id(id=47) -- wl_callback@47eb.destroyed after 0.0178s ↲
 2.2981 A: wl_callback@47eb.done(callback_data=37631531) ↲
 2.2983 A: wl_callback@44em.done(callback_data=40315) ↲
 2.2983 A: wl_buffer@43c.release() ↲
 2.2984 A: → wl_surface@33a.attach(buffer=wl_buffer@43c, x=0, y=0)
 2.2984 A: → wl_surface@33a.damage_buffer(x=0, y=0, width=2147483647, height=2147483647)
 2.2985 A: → wl_surface@33a.commit()
 2.2985 A: → wl_display@1a.sync(callback=new wl_callback@44en)
 2.2985 A: → wl_surface@33a.frame(callback=new wl_callback@47ec)
 2.2985 A: → wl_surface@33a.commit()
 2.2987 A: wl_display@1a.delete_id(id=44) -- wl_callback@44en.destroyed after 0.0002s ↲
```

<details>
  <summary>kitty-debug</summary>

```
kitty 0.43.1 created by Kovid Goyal
Linux kenfrmwk 6.17.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 06 Oct 2025 18:48:29 +0000 x86_64
S{PRETTY_NAME} 6.17.1-arch1-1 (/dev/tty)

DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
Running under: Wayland (GNOME Shell 49.0) missing: blur server_side_decorations layer_shell icon
OpenGL: '4.6 (Core Profile) Mesa 25.2.4-arch1.1' Detected version: 4.6
Frozen: False
Fonts:
  medium: JetBrainsMono-Regular: /usr/share/fonts/TTF/JetBrainsMono-Regular.ttf:0
          Features: ()
    bold: JetBrainsMono-SemiBold: /usr/share/fonts/TTF/JetBrainsMono-SemiBold.ttf:0
          Features: ()
  italic: JetBrainsMono-Italic: /usr/share/fonts/TTF/JetBrainsMono-Italic.ttf:0
          Features: ()
      bi: JetBrainsMono-SemiBoldItalic: /usr/share/fonts/TTF/JetBrainsMono-SemiBoldItalic.ttf:0
          Features: ()
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/fish
System color scheme: dark. Applied color theme type: none
Loaded config files:
  /home/keynslug/.config/kitty/kitty.conf

Config options different from defaults:
copy_on_select                a1
cursor_blink_interval         (-1.0, kitty.options.utils.EasingFunction(type='cubic-bezier', cubic_bezier_points=(0.42, 0.0, 0.58, 1.0)), kitty.options.utils.EasingFunction())
cursor_stop_blinking_after    0.1
cursor_trail                  50
cursor_trail_decay            (0.1, 0.2)
cursor_trail_start_threshold  12
disable_ligatures             1
editor                        /usr/bin/nano
enable_audio_bell             False
enabled_layouts               ['splits', 'fat', 'stack']
font_family                   Jetbrains Mono
font_size                     9.0
hide_window_decorations       1
inactive_text_alpha           0.6
initial_window_height         (640, 'px')
initial_window_width          (1000, 'px')
input_delay                   5
kitty_mod                     super
linux_display_server          wayland
remember_window_size          False
scrollback_pager_history_size 10485760
shell                         /usr/bin/fish
strip_trailing_spaces         smart
tab_bar_min_tabs              1
tab_bar_style                 powerline
tab_powerline_style           slanted
touch_scroll_multiplier       10.0
visual_bell_duration          (0.16, kitty.options.utils.EasingFunction(type='cubic-bezier', cubic_bezier_points=(0, 0.0, 1.0, 1.0)), kitty.options.utils.EasingFunction())
window_padding_width          FloatEdges(left=3.0, top=3.0, right=3.0, bottom=3.0)
Changed mouse actions:
	right press ungrabbed →  mouse_select_command_output
Added shortcuts:
	ctrl+c →  copy_and_clear_or_interrupt
	ctrl+v →  paste_from_clipboard
	kitty_mod+/ →  next_window
	kitty_mod+\ →  launch --type=window --cwd=current --location=vsplit
	kitty_mod+ctrl+down →  scroll_line_down
	kitty_mod+ctrl+page_down →  scroll_page_down
	kitty_mod+ctrl+page_up →  scroll_page_up
	kitty_mod+ctrl+up →  scroll_line_up
	kitty_mod+insert →  paste_from_selection
	kitty_mod+p > l →  kitten hints --type hyperlink, kitten hints --type path, kitten hints --type path --program -, kitten hints --type linenum, kitten hints --type hash --program -, kitten hints --type word --program -, kitten hints --type line --program -
	kitty_mod+shift+, →  scroll_to_prompt -1
	kitty_mod+shift+- →  change_font_size all -1.0
	kitty_mod+shift+/ →  previous_window
	kitty_mod+shift+0 →  tenth_window
	kitty_mod+shift+1 →  first_window
	kitty_mod+shift+2 →  second_window
	kitty_mod+shift+3 →  third_window
	kitty_mod+shift+4 →  fourth_window
	kitty_mod+shift+5 →  fifth_window
	kitty_mod+shift+6 →  sixth_window
	kitty_mod+shift+7 →  seventh_window
	kitty_mod+shift+8 →  eighth_window
	kitty_mod+shift+9 →  ninth_window
	kitty_mod+shift+= →  change_font_size all +1.0
	kitty_mod+shift+\ →  launch --type=window --cwd=current --location=hsplit
	kitty_mod+shift+` →  move_window_to_top
	kitty_mod+shift+a →  launch --stdin-source=@screen_scrollback --type=clipboard
	kitty_mod+shift+c →  kitten ./kitty-grab/grab.py
	kitty_mod+shift+escape →  kitty_shell window
	kitty_mod+shift+f5 →  load_config_file
	kitty_mod+shift+f6 →  debug_config
	kitty_mod+shift+g →  show_last_visited_command_output
	kitty_mod+shift+h →  show_scrollback
	kitty_mod+shift+l →  next_layout
	kitty_mod+shift+n →  new_os_window
	kitty_mod+shift+v →  paste_from_buffer a1
	kitty_mod+shift+w →  close_tab
Removed shortcuts:
	kitty_mod+p > f →  kitten hints --type hyperlink, kitten hints --type linenum, kitten hints --type hash --program -, kitten hints --type word --program -, kitten hints --type line --program -, kitten hints --type path, kitten hints --type path --program -
Changed shortcuts:
	kitty_mod+, →  previous_tab
	kitty_mod+. →  next_tab
	kitty_mod+[ →  move_tab_backward
	kitty_mod+] →  move_tab_forward
	kitty_mod+backspace →  combine : clear_terminal to_cursor active : clear_terminal scrollback active
	kitty_mod+down →  neighboring_window down
	kitty_mod+enter →  launch --type=tab --cwd=current --location=neighbor
	kitty_mod+left →  neighboring_window left
	kitty_mod+right →  neighboring_window right
	kitty_mod+up →  neighboring_window up
	kitty_mod+x →  toggle_layout stack
Colors:
	active_border_color           #49e998   
	background                    #0c1115   
	color0                        #2e343c   
	color1                        #bd0f2f   
	color10                       #49e998   
	color11                       #fddf6e   
	color12                       #2a8bc1   
	color13                       #ea4727   
	color14                       #a0b6d3   
	color2                        #35a770   
	color3                        #fb9435   
	color4                        #1f5872   
	color5                        #bd2523   
	color6                        #778397   
	color7                        #ffffff   
	color8                        #404a55   
	color9                        #bd0f2f   
	cursor                        #6c6c6c   
	foreground                    #ffffff   
	inactive_border_color         #0c1115   
	selection_background          #404a55   
	selection_foreground          #ffffff   

Important environment variables seen by the kitty process:
	PATH                                /home/keynslug/ws/pg/yandex-cloud/bin:/usr/local/bin:/usr/bin:/home/keynslug/bin:/home/keynslug/.krew/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/keynslug/bin:/home/keynslug/.krew/bin
	LANG                                en_US.UTF-8
	EDITOR                              nano
	SHELL                               /bin/fish
	DISPLAY                             :0
	WAYLAND_DISPLAY                     wayland-0
	USER                                keynslug
	LC_MEASUREMENT                      en_GB.UTF-8
	LC_MONETARY                         en_GB.UTF-8
	LC_NUMERIC                          en_GB.UTF-8
	LC_PAPER                            en_GB.UTF-8
	LC_TIME                             en_GB.UTF-8
	XDG_DATA_DIRS                       /home/keynslug/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
	XDG_RUNTIME_DIR                     /run/user/1000
	LC_ADDRESS                          en_GB.UTF-8
	LC_TELEPHONE                        en_GB.UTF-8
	XDG_CURRENT_DESKTOP                 GNOME
	XDG_MENU_PREFIX                     gnome-
	XDG_SESSION_CLASS                   user
	XDG_SESSION_DESKTOP                 gnome
	XDG_SESSION_TYPE                    wayland
```

</details>

**Comment by kovidgoyal** [comment]
Definitely does not reproduce for me, kitty doesnt even tick the event
loop once the cursor stops blinking

Steps I tried (under hyprland)

WAYLAND_DEBUG=1 kitty --config=NONE -o cursor_blink_interval=0

open two tabs one running htop and switch to the empty tab

there is no wayland debug output once the mouse stops moving indicating
that kitty is not communicating with wayland at all

**Comment by keynslug** [comment]
Thanks for looking into it.

You're right that empty config does not trigger it. And I managed to reproduce it with:
```
env WAYLAND_DEBUG=1 usr/bin/kitty --config=NONE \
-o cursor_stop_blinking_after='0.1' \
-o disable_ligatures='cursor' \
-o linux_display_server='wayland' \
-o hide_window_decorations='yes' \
-o tab_bar_min_tabs='1'
```

Notably `disable_ligatures` seems to induce this behavior. Using both `always` and `never` helps, this per-frame activity is visible only if it's `cursor`.

**Comment by SaltyKitkat** [comment]
> Notably `disable_ligatures` seems to induce this behavior. Using both `always` and `never` helps, this per-frame activity is visible only if it's `cursor`.

Thanks. I missed this config option. I also have this set to 'cursor'.

**Comment by kovidgoyal** [comment]
OK I will look at it when I have a minute
